"""Alembic Schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-05
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table(
        "season",
        sa.Column("season", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("game", sa.Text(), nullable=False),
        sa.Column("rule_pack_version", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("season", name=op.f("pk_season")),
        schema="core",
        comment="One row per FTC season, keyed by its starting year: 2025 is the 2025-26 season.",
    )
    op.create_table(
        "team",
        sa.Column("team_number", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("rookie_year", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("team_number", name=op.f("pk_team")),
        schema="core",
        comment="One row per team number, holding only what does not vary by season. The rest is in team_season.",
    )
    op.create_table(
        "ingest_conflict",
        sa.Column("ingest_conflict_id", sa.UUID(), nullable=False),
        sa.Column("observed_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("table_name", sa.Text(), nullable=False),
        sa.Column("key", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("stored", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("incoming", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("payload_hash", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("ingest_conflict_id", name=op.f("pk_ingest_conflict")),
        schema="raw",
        comment="Conflicts between sources are recorded, not resolved. The FTC Events value is the more trusted and is the one that lands in the fact table; both readings are kept here.",
    )
    op.create_index(
        "ix_ingest_conflict_table_observed",
        "ingest_conflict",
        ["table_name", "observed_at_utc"],
        unique=False,
        schema="raw",
    )
    op.create_table(
        "ingest_diff",
        sa.Column("ingest_diff_id", sa.UUID(), nullable=False),
        sa.Column("observed_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("table_name", sa.Text(), nullable=False),
        sa.Column("key", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
        sa.Column("before", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("payload_hash", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("ingest_diff_id", name=op.f("pk_ingest_diff")),
        schema="raw",
        comment="What a row held before an upstream change overwrote it. The fact tables keep current values only.",
    )
    op.create_index(
        "ix_ingest_diff_table_observed", "ingest_diff", ["table_name", "observed_at_utc"], unique=False, schema="raw"
    )
    op.create_table(
        "raw_payload",
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("fetched_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("byte_length", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("payload_hash", name=op.f("pk_raw_payload")),
        schema="raw",
        comment="Bodies live on disk, content-addressed and gzipped, reachable only through Warehouse tooling.",
    )
    op.create_index(
        "ix_raw_payload_endpoint_fetched", "raw_payload", ["endpoint", "fetched_at_utc"], unique=False, schema="raw"
    )
    op.create_table(
        "event",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("division_code", sa.Text(), nullable=True),
        sa.Column("region_code", sa.Text(), nullable=True),
        sa.Column("league_code", sa.Text(), nullable=True),
        sa.Column("field_count", sa.SmallInteger(), nullable=True),
        sa.Column("date_start", sa.Date(), nullable=False),
        sa.Column("date_end", sa.Date(), nullable=True),
        sa.Column("venue", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state_prov", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=True),
        sa.Column("timezone_assumed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["season"], ["core.season.season"], name=op.f("fk_event_season")),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_event")),
        sa.UniqueConstraint("season", "code", name="uq_event_season_code"),
        schema="core",
        comment="One row per in-person event. Remote and hybrid events are absent.",
    )
    op.create_index("ix_event_region_code", "event", ["season", "region_code"], unique=False, schema="core")
    op.create_index("ix_event_season_date_start", "event", ["season", "date_start"], unique=False, schema="core")
    op.create_table(
        "rule_pack",
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("game", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("source_file", sa.Text(), nullable=False),
        sa.Column("rp_win", sa.Integer(), nullable=True),
        sa.Column("rp_tie", sa.Integer(), nullable=True),
        sa.Column("rp_loss", sa.Integer(), nullable=True),
        sa.Column("has_bonus_rp", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("bonus_rp", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("alliance_size", sa.Integer(), server_default=sa.text("2"), nullable=False),
        sa.Column("ranking_formula", sa.Text(), nullable=True),
        sa.Column("tiebreakers", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("playoff_structure", sa.Text(), nullable=True),
        sa.Column("alliance_brackets", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("playoff_implemented", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("advancement_implemented", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("loaded_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["season"], ["core.season.season"], name=op.f("fk_rule_pack_season")),
        sa.PrimaryKeyConstraint("season", name=op.f("pk_rule_pack")),
        schema="core",
        comment="Processed from files in this repo manually created off of the game manuals.",
    )
    op.create_table(
        "team_season",
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column("name_full", sa.Text(), nullable=True),
        sa.Column("name_short", sa.Text(), nullable=True),
        sa.Column("home_state", sa.Text(), nullable=True),
        sa.Column("home_country", sa.Text(), nullable=True),
        sa.Column("home_region", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["season"], ["core.season.season"], name=op.f("fk_team_season_season")),
        sa.ForeignKeyConstraint(["team_number"], ["core.team.team_number"], name=op.f("fk_team_season_team_number")),
        sa.PrimaryKeyConstraint("season", "team_number", name=op.f("pk_team_season")),
        schema="core",
    )
    op.create_index("ix_team_season_home_region", "team_season", ["season", "home_region"], unique=False, schema="core")
    op.create_table(
        "ingest_run",
        sa.Column("ingest_run_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.Enum("season", "event", name="ingest_scope", schema="raw"), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("payload_hash", sa.Text(), nullable=True),
        sa.Column("last_checked_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_changed_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_status", sa.Integer(), nullable=True),
        sa.Column("run_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("check_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("empty_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_written", sa.Integer(), nullable=True),
        sa.Column("notes", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "(scope = 'season' AND event_id IS NULL) OR (scope = 'event' AND event_id IS NOT NULL)",
            name=op.f("ck_ingest_run_scope_matches_event_id"),
        ),
        sa.ForeignKeyConstraint(
            ["payload_hash"], ["raw.raw_payload.payload_hash"], name=op.f("fk_ingest_run_payload_hash")
        ),
        sa.PrimaryKeyConstraint("ingest_run_id", name=op.f("pk_ingest_run")),
        schema="raw",
        comment="One row per (scope, endpoint), holding the timestamp to hand back on the next request. A reply saying nothing changed only moves last_checked_at_utc; a reply carrying data this table has not seen before increments run_count.",
    )
    op.create_index(
        "ingest_cursor_event",
        "ingest_run",
        ["event_id", "endpoint"],
        unique=True,
        schema="raw",
        postgresql_where=sa.text("event_id IS NOT NULL"),
    )
    op.create_index(
        "ingest_cursor_season",
        "ingest_run",
        ["season", "endpoint"],
        unique=True,
        schema="raw",
        postgresql_where=sa.text("event_id IS NULL"),
    )
    op.create_table(
        "advancement_points",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("detail", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_advancement_points_event_id")),
        sa.ForeignKeyConstraint(
            ["team_number"], ["core.team.team_number"], name=op.f("fk_advancement_points_team_number")
        ),
        sa.PrimaryKeyConstraint("event_id", "team_number", name=op.f("pk_advancement_points")),
        schema="core",
        comment="Official advancement points for completed events. 2025 onward.",
    )
    op.create_table(
        "advancement_slot",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_advancement_slot_event_id")),
        sa.ForeignKeyConstraint(
            ["team_number"], ["core.team.team_number"], name=op.f("fk_advancement_slot_team_number")
        ),
        sa.PrimaryKeyConstraint("event_id", "slot", name=op.f("pk_advancement_slot")),
        schema="core",
        comment="The order in which advancement slots were assigned.",
    )
    op.create_table(
        "award",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("award_code", sa.Integer(), nullable=False),
        sa.Column("series", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), server_default=sa.text("'ftc_events'"), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_award_event_id")),
        sa.ForeignKeyConstraint(["team_number"], ["core.team.team_number"], name=op.f("fk_award_team_number")),
        sa.PrimaryKeyConstraint("event_id", "award_code", "series", name=op.f("pk_award")),
        schema="core",
        comment="Judged team awards that were won.",
    )
    op.create_table(
        "event_advancement",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("advances_to", sa.Text(), nullable=True),
        sa.Column("slots", sa.Integer(), nullable=True),
        sa.Column("slots_first_championship", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_event_advancement_event_id")),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_event_advancement")),
        schema="core",
        comment="How many teams the event sends and where.",
    )
    op.create_table(
        "event_team",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column("first_observed_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_event_team_event_id")),
        sa.ForeignKeyConstraint(["team_number"], ["core.team.team_number"], name=op.f("fk_event_team_team_number")),
        sa.PrimaryKeyConstraint("event_id", "team_number", name=op.f("pk_event_team")),
        schema="core",
        comment="One row per team that competed at an event, as FTC Events listed them at schedule generation. Written once per event.",
    )
    op.create_index("ix_event_team_event_id", "event_team", ["event_id"], unique=False, schema="core")
    op.create_index(
        "ix_event_team_team_number_event_id", "event_team", ["team_number", "event_id"], unique=False, schema="core"
    )
    op.create_table(
        "match",
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "PRACTICE", "QUALIFICATION", "SEMIFINAL", "FINAL", "PLAYOFF", "OTHER", name="match_level", schema="core"
            ),
            nullable=False,
        ),
        sa.Column("series", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("match_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_time_utc", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("start_time_local", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("actual_start_time_utc", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("actual_start_time_local", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("post_result_time_utc", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("post_result_time_local", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("modified_on_utc", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("score_red_final", sa.Integer(), nullable=True),
        sa.Column("score_blue_final", sa.Integer(), nullable=True),
        sa.Column("score_red_auto", sa.Integer(), nullable=True),
        sa.Column("score_blue_auto", sa.Integer(), nullable=True),
        sa.Column("score_red_foul", sa.Integer(), nullable=True),
        sa.Column("score_blue_foul", sa.Integer(), nullable=True),
        sa.Column("ingested_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_match_event_id")),
        sa.PrimaryKeyConstraint("match_id", name=op.f("pk_match")),
        sa.UniqueConstraint("event_id", "level", "series", "match_number", name="uq_match_natural_key"),
        schema="core",
        comment="One row per schedule slot, holding the latest result. We cannot distinguish between a correction and a replay, so a changed payload overwrites the row in place and the pre-replay result is gone.",
    )
    op.create_table(
        "ranking",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=True),
        sa.Column("losses", sa.Integer(), nullable=True),
        sa.Column("ties", sa.Integer(), nullable=True),
        sa.Column("matches_played", sa.Integer(), nullable=True),
        sa.Column("qual_average", sa.Float(), nullable=True),
        sa.Column("dq", sa.Integer(), nullable=True),
        sa.Column("sort_order_1", sa.Float(), nullable=True),
        sa.Column("sort_order_2", sa.Float(), nullable=True),
        sa.Column("sort_order_3", sa.Float(), nullable=True),
        sa.Column("sort_order_4", sa.Float(), nullable=True),
        sa.Column("sort_order_5", sa.Float(), nullable=True),
        sa.Column("sort_order_6", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_ranking_event_id")),
        sa.ForeignKeyConstraint(["team_number"], ["core.team.team_number"], name=op.f("fk_ranking_team_number")),
        sa.PrimaryKeyConstraint("event_id", "team_number", name=op.f("pk_ranking")),
        schema="core",
        comment="Official published rankings, one row per event and team.",
    )
    op.create_table(
        "rule_pack_component",
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("level", sa.Enum("alliance", "team", name="component_level", schema="core"), nullable=False),
        sa.Column(
            "kind", sa.Enum("numeric", "boolean", "enum", "array", name="component_kind", schema="core"), nullable=False
        ),
        sa.Column("is_subtotal", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_derived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("column_name", sa.Text(), nullable=False),
        sa.Column("partition_group", sa.Text(), nullable=True),
        sa.Column("phase", sa.Text(), nullable=True),
        sa.Column("recovered_from", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("state_scoring", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["season"], ["core.rule_pack.season"], name="fk_component_season"),
        sa.PrimaryKeyConstraint("season", "name", name=op.f("pk_rule_pack_component")),
        sa.UniqueConstraint("season", "column_name", name="uq_component_season_column"),
        schema="core",
        comment="One row per line item a match breakdown reports, and the phase totals those add up to.",
    )
    op.create_table(
        "fit_run",
        sa.Column("fit_run_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column("prior_version", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("started_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("finished_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("notes", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_fit_run_event_id")),
        sa.PrimaryKeyConstraint("fit_run_id", name=op.f("pk_fit_run")),
        schema="derived",
    )
    op.create_index(
        "fit_run_live_uniq",
        "fit_run",
        ["event_id", "model", "model_version", "prior_version"],
        unique=True,
        schema="derived",
        postgresql_where=sa.text("event_id IS NOT NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        "fit_run_batch_uniq",
        "fit_run",
        ["model", "season", "model_version", "prior_version"],
        unique=True,
        schema="derived",
        postgresql_where=sa.text("event_id IS NULL AND finished_at_utc IS NOT NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "team_event_opr",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column("opr_total", sa.Float(), nullable=True),
        sa.Column("opr_total_np", sa.Float(), nullable=True),
        sa.Column("opr_auto", sa.Float(), nullable=True),
        sa.Column("opr_teleop", sa.Float(), nullable=True),
        sa.Column("computed_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_team_event_opr_event_id")),
        sa.ForeignKeyConstraint(["team_number"], ["core.team.team_number"], name=op.f("fk_team_event_opr_team_number")),
        sa.PrimaryKeyConstraint("event_id", "team_number", name=op.f("pk_team_event_opr")),
        schema="derived",
    )
    op.create_table(
        "playoff_alliance",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("alliance_number", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("captain", sa.Integer(), nullable=True),
        sa.Column("round1", sa.Integer(), nullable=True),
        sa.Column("round2", sa.Integer(), nullable=True),
        sa.Column("ingested_at_utc", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["captain"], ["core.team.team_number"], name=op.f("fk_playoff_alliance_captain")),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_playoff_alliance_event_id")),
        sa.ForeignKeyConstraint(["round1"], ["core.team.team_number"], name=op.f("fk_playoff_alliance_round1")),
        sa.ForeignKeyConstraint(["round2"], ["core.team.team_number"], name=op.f("fk_playoff_alliance_round2")),
        sa.PrimaryKeyConstraint("event_id", "alliance_number", name=op.f("pk_playoff_alliance")),
        schema="core",
        comment="One row per playoff alliance, as FIRST publishes it.",
    )
    op.create_index("ix_playoff_alliance_captain", "playoff_alliance", ["captain"], unique=False, schema="core")
    op.create_table(
        "playoff_alliance_pick",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("pick_ordinal", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("alliance_number", sa.Integer(), nullable=True),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("CAPTAIN", "ACCEPT", "DECLINE", "REMOVE", name="alliance_pick_action", schema="core"),
            nullable=False,
        ),
        sa.Column("ingested_at_utc", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_playoff_alliance_pick_event_id")),
        sa.ForeignKeyConstraint(
            ["team_number"], ["core.team.team_number"], name=op.f("fk_playoff_alliance_pick_team_number")
        ),
        sa.PrimaryKeyConstraint("event_id", "pick_ordinal", name=op.f("pk_playoff_alliance_pick")),
        schema="core",
        comment="The selection in the order it happened. A DECLINE or REMOVE row records a team that ended up on no alliance.",
    )
    op.create_index(
        "ix_playoff_alliance_pick_team_number", "playoff_alliance_pick", ["team_number"], unique=False, schema="core"
    )
    op.create_table(
        "match_breakdown",
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("alliance", sa.Enum("RED", "BLUE", name="alliance", schema="core"), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["core.match.match_id"], name=op.f("fk_match_breakdown_match_id")),
        sa.PrimaryKeyConstraint("match_id", "alliance", name=op.f("pk_match_breakdown")),
        schema="core",
        comment="Per-alliance component scores, validated in the application against the season's rule pack",
    )
    op.create_table(
        "match_team",
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("station", sa.Text(), nullable=False),
        sa.Column("alliance", sa.Enum("RED", "BLUE", name="alliance", schema="core"), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column("surrogate", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("no_show", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("dq", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("on_field", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "alliance_role",
            sa.Enum("Captain", "FirstPick", "SecondPick", name="alliance_role", schema="core"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["match_id"], ["core.match.match_id"], name=op.f("fk_match_team_match_id")),
        sa.ForeignKeyConstraint(["team_number"], ["core.team.team_number"], name=op.f("fk_match_team_team_number")),
        sa.PrimaryKeyConstraint("match_id", "station", name=op.f("pk_match_team")),
        schema="core",
        comment="The team slot. Surrogate and no-show live here, not on the match.",
    )
    op.create_index("ix_match_team_team_number", "match_team", ["team_number"], unique=False, schema="core")
    op.create_table(
        "team_epa",
        sa.Column("fit_run_id", sa.UUID(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("as_of_match", sa.Integer(), nullable=True),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column("tag", sa.Text(), server_default=sa.text("'match'"), nullable=False),
        sa.Column("epa_norm", sa.Float(), nullable=True),
        sa.Column("epa_scaled", sa.Float(), nullable=False),
        sa.Column("scale_provisional", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("components", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "(tag = 'season_start') = (event_id IS NULL)", name=op.f("ck_team_epa_season_start_has_no_event")
        ),
        sa.CheckConstraint("tag IN ('season_start', 'pre_event', 'post_event', 'match')", name=op.f("ck_team_epa_tag")),
        sa.CheckConstraint("(event_id IS NULL) = (as_of_match IS NULL)", name=op.f("ck_team_epa_event_scope")),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_team_epa_event_id")),
        sa.ForeignKeyConstraint(
            ["fit_run_id"], ["derived.fit_run.fit_run_id"], name=op.f("fk_team_epa_fit_run_id"), ondelete="CASCADE"
        ),
        schema="derived",
    )
    op.create_index(
        "ix_team_epa_latest",
        "team_epa",
        ["season", "team_number", "model_version", sa.literal_column("as_of_match DESC")],
        unique=False,
        schema="derived",
    )
    op.create_index(
        "uq_team_epa_row",
        "team_epa",
        ["fit_run_id", "event_id", "team_number", "as_of_match", "tag"],
        unique=True,
        schema="derived",
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "team_pridge",
        sa.Column("fit_run_id", sa.UUID(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("as_of_match", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column("component", sa.Text(), server_default=sa.text("'total'"), nullable=False),
        sa.Column("pridge", sa.Float(), nullable=False),
        sa.Column("lambda_", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_team_pridge_event_id")),
        sa.ForeignKeyConstraint(
            ["fit_run_id"], ["derived.fit_run.fit_run_id"], name=op.f("fk_team_pridge_fit_run_id"), ondelete="CASCADE"
        ),
        sa.UniqueConstraint(
            "fit_run_id", "event_id", "team_number", "component", "as_of_match", name="uq_team_pridge_row"
        ),
        schema="derived",
    )
    op.create_index(
        "ix_team_pridge_latest",
        "team_pridge",
        ["season", "team_number", "model_version", sa.literal_column("as_of_match DESC")],
        unique=False,
        schema="derived",
    )
    op.create_table(
        "event_sim_run",
        sa.Column("sim_run_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("epa_version", sa.Text(), nullable=False),
        sa.Column("sim_version", sa.Text(), nullable=False),
        sa.Column("as_of_match", sa.Integer(), nullable=False),
        sa.Column("n_iterations", sa.Integer(), nullable=False),
        sa.Column("achieved_mcse", sa.Float(), nullable=False),
        sa.Column("computed_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["core.event.event_id"], name=op.f("fk_event_sim_run_event_id")),
        sa.PrimaryKeyConstraint("sim_run_id", name=op.f("pk_event_sim_run")),
        sa.UniqueConstraint("event_id", "epa_version", "sim_version", "as_of_match", name="uq_event_sim_run_key"),
        schema="derived",
    )
    op.create_table(
        "event_sim_result",
        sa.Column("sim_run_id", sa.UUID(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column("p_attend", sa.Float(), nullable=False),
        sa.Column("mean_rank", sa.Float(), nullable=True),
        sa.Column("rank_probabilities", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("p_captain", sa.Float(), nullable=False),
        sa.Column("p_selected", sa.Float(), nullable=False),
        sa.Column("p_win", sa.Float(), nullable=False),
        sa.Column("p_advance", sa.Float(), nullable=True),
        sa.Column("p_advance_first_championship", sa.Float(), nullable=True),
        sa.CheckConstraint("mean_rank >= 1", name=op.f("ck_event_sim_result_mean_rank")),
        sa.CheckConstraint(
            "p_attend BETWEEN 0 AND 1 AND p_captain BETWEEN 0 AND 1 AND p_selected BETWEEN 0 AND 1"
            " AND p_win BETWEEN 0 AND 1 AND p_advance BETWEEN 0 AND 1"
            " AND p_advance_first_championship BETWEEN 0 AND p_advance",
            name=op.f("ck_event_sim_result_probabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["sim_run_id"],
            ["derived.event_sim_run.sim_run_id"],
            name=op.f("fk_event_sim_result_sim_run_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sim_run_id", "team_number", name=op.f("pk_event_sim_result")),
        schema="derived",
    )
    op.create_table(
        "season_sim_run",
        sa.Column("sim_run_id", sa.UUID(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("region_code", sa.Text(), nullable=False),
        sa.Column("epa_version", sa.Text(), nullable=False),
        sa.Column("sim_version", sa.Text(), nullable=False),
        sa.Column("n_iterations", sa.Integer(), nullable=False),
        sa.Column("achieved_mcse", sa.Float(), nullable=False),
        sa.Column("computed_at_utc", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("sim_run_id", name=op.f("pk_season_sim_run")),
        sa.UniqueConstraint("season", "region_code", "epa_version", "sim_version", name="uq_season_sim_run_key"),
        schema="derived",
    )
    op.create_table(
        "season_sim_result",
        sa.Column("sim_run_id", sa.UUID(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.Column("p_attend_rcmp", sa.Float(), nullable=False),
        sa.Column("p_premier", sa.Float(), nullable=False),
        sa.Column("p_cmp", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "p_attend_rcmp BETWEEN 0 AND 1 AND p_premier BETWEEN 0 AND 1 AND p_cmp BETWEEN 0 AND 1",
            name=op.f("ck_season_sim_result_probabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["sim_run_id"],
            ["derived.season_sim_run.sim_run_id"],
            name=op.f("fk_season_sim_result_sim_run_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sim_run_id", "team_number", name=op.f("pk_season_sim_result")),
        schema="derived",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("season_sim_result", schema="derived")
    op.drop_table("season_sim_run", schema="derived")
    op.drop_table("event_sim_result", schema="derived")
    op.drop_table("event_sim_run", schema="derived")
    op.drop_index("ix_playoff_alliance_pick_team_number", table_name="playoff_alliance_pick", schema="core")
    op.drop_table("playoff_alliance_pick", schema="core")
    op.drop_index("ix_playoff_alliance_captain", table_name="playoff_alliance", schema="core")
    op.drop_table("playoff_alliance", schema="core")
    op.drop_index("ix_team_pridge_latest", table_name="team_pridge", schema="derived")
    op.drop_table("team_pridge", schema="derived")
    op.drop_index("uq_team_epa_row", table_name="team_epa", schema="derived", postgresql_nulls_not_distinct=True)
    op.drop_index("ix_team_epa_latest", table_name="team_epa", schema="derived")
    op.drop_table("team_epa", schema="derived")
    op.drop_index("ix_match_team_team_number", table_name="match_team", schema="core")
    op.drop_table("match_team", schema="core")
    op.drop_table("match_breakdown", schema="core")
    op.drop_table("team_event_opr", schema="derived")
    op.drop_index(
        "fit_run_batch_uniq",
        table_name="fit_run",
        schema="derived",
        postgresql_where=sa.text("event_id IS NULL AND finished_at_utc IS NOT NULL"),
    )
    op.drop_index(
        "fit_run_live_uniq", table_name="fit_run", schema="derived", postgresql_where=sa.text("event_id IS NOT NULL")
    )
    op.drop_table("fit_run", schema="derived")
    op.drop_table("rule_pack_component", schema="core")
    op.drop_table("ranking", schema="core")
    op.drop_table("match", schema="core")
    op.drop_index("ix_event_team_team_number_event_id", table_name="event_team", schema="core")
    op.drop_index("ix_event_team_event_id", table_name="event_team", schema="core")
    op.drop_table("event_team", schema="core")
    op.drop_table("event_advancement", schema="core")
    op.drop_table("award", schema="core")
    op.drop_table("advancement_slot", schema="core")
    op.drop_table("advancement_points", schema="core")
    op.drop_index(
        "ingest_cursor_season", table_name="ingest_run", schema="raw", postgresql_where=sa.text("event_id IS NULL")
    )
    op.drop_index(
        "ingest_cursor_event", table_name="ingest_run", schema="raw", postgresql_where=sa.text("event_id IS NOT NULL")
    )
    op.drop_table("ingest_run", schema="raw")
    op.drop_index("ix_team_season_home_region", table_name="team_season", schema="core")
    op.drop_table("team_season", schema="core")
    op.drop_table("rule_pack", schema="core")
    op.drop_index("ix_event_season_date_start", table_name="event", schema="core")
    op.drop_index("ix_event_region_code", table_name="event", schema="core")
    op.drop_table("event", schema="core")
    op.drop_index("ix_raw_payload_endpoint_fetched", table_name="raw_payload", schema="raw")
    op.drop_table("raw_payload", schema="raw")
    op.drop_index("ix_ingest_diff_table_observed", table_name="ingest_diff", schema="raw")
    op.drop_table("ingest_diff", schema="raw")
    op.drop_index("ix_ingest_conflict_table_observed", table_name="ingest_conflict", schema="raw")
    op.drop_table("ingest_conflict", schema="raw")
    op.drop_table("team", schema="core")
    op.drop_table("season", schema="core")
    # ### end Alembic commands ###

    for enum_name, schema in (
        ("match_level", "core"),
        ("alliance", "core"),
        ("alliance_role", "core"),
        ("alliance_pick_action", "core"),
        ("component_kind", "core"),
        ("component_level", "core"),
        ("ingest_scope", "raw"),
    ):
        op.execute(f"DROP TYPE IF EXISTS {schema}.{enum_name}")
